### ISSUE TITLE
iOS does not support frameworks

### ISSUE THREAD

**Issue by jasarien** [wordnik/wordkit#1]
The wordkit iOS SDK is provided as a framework.

iOS does not support frameworks and instead favours static libraries.
While it may be possible to link against a framework in an iOS project, any app that does so will be rejected during review.

It would be appropriate to provide a static library for the iOS wordkit SDK rather than a framework.

**Comment by fehguy** [comment]
Hi Jasarien, take a look here:

http://landonf.bikemonkey.org/code/iphone/iPhone_Framework_Support.20081202.html

The supplied iOS framework includes a static library instead of the usual dynamic library; when the application binary is linked, it will be linked statically as expected. The framework bundle itself is just an easy way to include both headers and the static library in a single bundle.

**Comment by jasarien** [comment]
Ah. This I did not know.. Thanks :)

**Comment by fehguy** [comment]
Sure thing, thanks for reaching out on this
